### ISSUE TITLE
vispy.visuals doesn't contain CompoundVisual     

### ISSUE THREAD

**Issue by anl13** [cvfish/VideoPopup#1]
In file `video_popup/visualization/vispy_util_persp.py`, line15 is 
```python
from vispy.visuals import CompoundVisual
```
However, I can't find a file named `CompoundVisual` in `vispy/visuals`. Every time it runs to `vispy_util_persp.py`, it would reports a bug: 
```shell
File "/home/al17/Projects/VideoPopup/video_popup/visualization/vispy_util_persp.py
", line 15, in <module>                               
    from vispy.visuals import CompoundVisual                             
ImportError: cannot import name CompoundVisual
```
So, how to fix it?

**Comment by cvfish** [comment]
Have you installed vispy? It's in https://github.com/vispy/vispy/blob/master/vispy/visuals/visual.py, line 523

**Comment by anl13** [comment]
Thank you, I have solved the problem. I installed an old version of `vispy`, which doesn't have `CompoundVisual` in `visual.py`. Now I install the newest one, and problem solved. Thanks a lot!
