### ISSUE TITLE
failed to import module _transformations

### ISSUE THREAD

**Issue by anl13** [cvfish/VideoPopup#2]
When I try to run `reconstruction_bird.py`, I get following output: 
```shell 
al17@al17-All-Series:~/Projects/VideoPopup/video_popup/reconstruction$ python reconstruction_bird.py 
/home/al17/Projects/VideoPopup/video_popup/utils/transformations.py:1899: UserWarning: failed to import module _transformations
  warnings.warn("failed to import module %s" % name)
0
```
It seems that I can't import `_transformations`. But where is `_transformations`? What is it? I think I have not idea about it yet. Could I give some advice?

**Comment by cvfish** [comment]
It's a warning, which you can safely ignore. The code will run and generate the results you need.

**Comment by anl13** [comment]
Ok, thank you~
